from typing import Protocol


class MessagingPort(Protocol):
    async def send_text(self, to: str, body: str) -> None: ...
    async def send_image(self, to: str, image_url: str, caption: str) -> None: ...
    async def send_template(self, to: str, template: str, params: dict) -> None: ...
