from __future__ import annotations

from typing import Protocol
from uuid import UUID

from apron.domain.models import (
    InventoryItem,
    MealPlan,
    Order,
    Recipe,
    ShoppingListItem,
    UserProfile,
)


class UserRepository(Protocol):
    async def get_by_phone(self, phone: str) -> UserProfile | None: ...
    async def get_by_id(self, user_id: UUID) -> UserProfile: ...
    async def save(self, user: UserProfile) -> UserProfile: ...
    async def update(self, user: UserProfile) -> UserProfile: ...
    async def list_all(self) -> list: ...


class InventoryRepository(Protocol):
    async def get_all(self, user_id: UUID) -> list[InventoryItem]: ...
    async def upsert(self, item: InventoryItem) -> InventoryItem: ...
    async def bulk_upsert(self, items: list[InventoryItem]) -> list[InventoryItem]: ...
    async def delete(self, item_id: UUID) -> None: ...


class MealPlanRepository(Protocol):
    async def get_current(self, user_id: UUID) -> MealPlan | None: ...
    async def save(self, plan: MealPlan) -> MealPlan: ...
    async def update(self, plan: MealPlan) -> MealPlan: ...


class RecipeRepository(Protocol):
    async def get_favorites(self, user_id: UUID) -> list[Recipe]: ...
    async def save_favorite(self, user_id: UUID, recipe: Recipe) -> None: ...
    async def search(self, query: str, filters: dict) -> list[Recipe]: ...


class OrderRepository(Protocol):
    async def save(self, order: Order) -> Order: ...
    async def get_history(self, user_id: UUID, limit: int = 20) -> list[Order]: ...


class ShoppingListRepository(Protocol):
    async def get_list(self, user_id: UUID) -> list[ShoppingListItem]: ...
    async def add_items(self, items: list[ShoppingListItem]) -> None: ...
    async def mark_purchased(self, item_ids: list[UUID]) -> None: ...
    async def clear(self, user_id: UUID) -> None: ...
